[project]
name = "ddmy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.27.2",
    "parsel>=1.9.1",
    "pyside6-fluent-widgets[full]>=1.7.1",
    "qasync>=0.27.1",
]
